version: '3.7'
services:
    app:
        build: .
        ports:
            - ${PORT:-8000}:80
        environment:
            - PORT=80
        volumes:
            - .:/app
        command: 'npm start'
